IF NOT EXISTS(SELECT 1 FROM [TCGCT].[Games] WHERE [Name] = 'MTG')
BEGIN
    INSERT INTO TCGCT.Games VALUES ('MTG')
END

IF NOT EXISTS(SELECT 1 FROM [TCGCT].[Games] WHERE [Name] = 'FAB')
BEGIN
    INSERT INTO TCGCT.Games VALUES ('FAB')
END